CREATE TABLE tutores (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome VARCHAR(255) NOT NULL,
                         email VARCHAR(255)
);

CREATE TABLE pets (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      nome VARCHAR(255) NOT NULL,
                      especie VARCHAR(255) NOT NULL,
                      tutor_id BIGINT NOT NULL,

                      CONSTRAINT fk_pet_tutor
                          FOREIGN KEY (tutor_id)
                              REFERENCES tutores(id)
);

CREATE TABLE medicacoes (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome VARCHAR(255) NOT NULL,
                            horario TIME NOT NULL,
                            obrigatoria BOOLEAN,
                            pet_id BIGINT,

                            CONSTRAINT fk_medicacao_pet
                                FOREIGN KEY (pet_id)
                                    REFERENCES pets(id)
);

CREATE TABLE atividades (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tipo VARCHAR(255),
                           data DATE,
                           pontos INTEGER,
                           pet_id BIGINT,

                           CONSTRAINT fk_atividade_pet
                               FOREIGN KEY (pet_id)
                                   REFERENCES pets(id)
);